name: Prevent Tag Pushes

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  prevent-tag-push:
    runs-on: ubuntu-latest
    steps:
      - name: Block tag push
        run: |
          echo "Direct tag pushes are not allowed. Please create tags via releases or ask the repository maintainer."
          exit 1
